import { SpaceXLaunch, SpaceXRocket } from '@/types/spacex';

export const mockLaunches: SpaceXLaunch[] = [
  {
    id: '1',
    name: 'Test Mission 1',
    date_utc: '2024-01-15T10:00:00.000Z',
    date_local: '2024-01-15T05:00:00-05:00',
    success: true,
    upcoming: false,
    details: 'This is a test mission description.',
    flight_number: 1,
    rocket: 'rocket1',
    links: {
      patch: {
        small: 'https://example.com/patch-small.png',
        large: 'https://example.com/patch-large.png',
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: 'https://example.com/presskit',
      webcast: 'https://youtube.com/watch?v=test',
      youtube_id: 'test',
      article: 'https://example.com/article',
      wikipedia: 'https://wikipedia.org/test',
    },
  },
  {
    id: '2',
    name: 'Failed Mission',
    date_utc: '2023-12-01T15:30:00.000Z',
    date_local: '2023-12-01T10:30:00-05:00',
    success: false,
    upcoming: false,
    details: 'This mission unfortunately failed.',
    flight_number: 2,
    rocket: 'rocket1',
    links: {
      patch: {
        small: null,
        large: null,
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: null,
      youtube_id: null,
      article: null,
      wikipedia: null,
    },
  },
  {
    id: '3',
    name: 'Upcoming Mission',
    date_utc: '2025-06-01T12:00:00.000Z',
    date_local: '2025-06-01T08:00:00-04:00',
    success: null,
    upcoming: true,
    details: 'Exciting upcoming mission.',
    flight_number: 3,
    rocket: 'rocket2',
    links: {
      patch: {
        small: 'https://example.com/upcoming-patch.png',
        large: 'https://example.com/upcoming-patch-large.png',
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: null,
      youtube_id: null,
      article: null,
      wikipedia: null,
    },
  },
];

export const mockRockets: Record<string, SpaceXRocket> = {
  rocket1: {
    id: 'rocket1',
    name: 'Falcon 9',
    type: 'rocket',
    active: true,
    stages: 2,
    boosters: 0,
    cost_per_launch: 62000000,
    success_rate_pct: 97,
    first_flight: '2010-06-04',
    country: 'United States',
    company: 'SpaceX',
    description: 'Falcon 9 is a reusable, two-stage rocket designed and manufactured by SpaceX.',
  },
  rocket2: {
    id: 'rocket2',
    name: 'Falcon Heavy',
    type: 'rocket',
    active: true,
    stages: 2,
    boosters: 2,
    cost_per_launch: 90000000,
    success_rate_pct: 100,
    first_flight: '2018-02-06',
    country: 'United States',
    company: 'SpaceX',
    description: 'Falcon Heavy is a partially reusable heavy-lift launch vehicle.',
  },
};